site_name: Tako Engine
# site_url:
repo_url: https://github.com/TakoEngine/tako
nav:
  - index.md
  - reflection.md
theme:
  name: material
  palette:
    primary: deep purple
    accent: pink
plugins:
  - privacy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
