name: Prebuilt Devcontainer
on:
  push:
    branches:
    - 'main'

jobs:
  Setup:
    if: github.repository_owner == 'TakoEngine'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Emscripten Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/TakoEngine/devcontainer-emscripten
          configFile: .devcontainer/emscripten/devcontainer.json
      - name: Build Linux Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/TakoEngine/devcontainer-linux
          configFile: .devcontainer/linux/devcontainer.json
